version: 2

jobs:
  build:
    <<: *defaults
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm install
      - run: npm run build

  release:
    <<: *defaults
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm install semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/github @semantic-release/npm @semantic-release/commit-analyzer @semantic-release/release-notes-generator @qiwi/semantic-release-gh-pages-plugin
      - run: git checkout .
      - run: ./node_modules/.bin/semantic-release

workflows:
  version: 2
  analysis:
    jobs:
      - build:
          filters: *filter-only-semantic-pr

  release:
    jobs:
      - build:
          filters: *filter-only-master
      - hold:
          filters: *filter-only-master
          type: approval
          requires:
            - build
      - release:
          filters: *filter-only-master
          requires:
            - hold
